version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
#    expose:
#      - 5432
    networks:
      - db_nw
  web:
    build: .
    restart: always
    env_file:
      - .env
    expose:
      - 8080
    networks:
      - db_nw
      - flask_nw
      - default
    depends_on:
      - db
  huey:
    image: full-stack-vrp_web
    restart: always
    command: bash -c "huey_consumer.py periodic_timer.huey"
    env_file:
      - .env
    networks:
      - db_nw
      - flask_nw
      - default
    depends_on:
      - db
      - web
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - web:web
networks:
  db_nw:
    driver: bridge
  flask_nw:
    driver: bridge
volumes:
  pg-data: